name: omniedge openwrt docker cross build

on:
  push:
    branches:
      - dev
    tags:
      - 'v*.*.*'
jobs:
  build:
    name: Docker cross build
    env:
      ENVIRONMENT: ${{ github.event.inputs.env || 'dev' }}
      TAG: ${{ github.event.inputs.tag }}
    strategy:
      matrix:
        platform: [mips ]
    runs-on: ubuntu-latest
    
    steps:
      - name: setup env to prod if tag is not empty
        if: ${{ env.TAG }}
        run: |
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV

      - name: Checkout without tag
        if: ${{ !env.TAG }}
        uses: actions/checkout@master

      - name: Checkout with tag
        uses: actions/checkout@master
        if: ${{ env.TAG }}
        with:
          ref: ${{ env.TAG }}
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          set -x
          docker version
          docker build -t local -f docker/openwrt/Dockerfile-ubuntu-${{ matrix.platform }} .
          docker run --name omniedge -d local
      - name: copy file
        run: |
          docker cp omniedge:/app/omniedge.zip ./omniedge.zip
          mv ./omniedge.zip ./omniedge-${{ github.ref_name }}-openwrt-${{ matrix.platform }}.zip
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          path: omniedge-${{ github.ref_name }}-openwrt-${{ matrix.platform }}.zip
          name: omniedge-${{ github.ref_name }}-openwrt-${{ matrix.platform }}.zip
          if-no-files-found: error
          
      - name: Upload package to GitHub Release
        uses: svenstaro/upload-release-action@v2
        # if: "startsWith(github.ref, 'refs/tags/')"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          overwrite: true
          file: omniedge-${{ github.ref_name }}-openwrt-${{ matrix.platform }}.zip
          tag: ${{ github.ref }}